// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package news

import (
	"context"
	"github.com/Iiqbal2000/bareknews"
	"github.com/google/uuid"
	"sync"
)

// Ensure, that RepositoryMock does implement Repository.
// If this is not the case, regenerate this file with moq.
var _ Repository = &RepositoryMock{}

// RepositoryMock is a mock implementation of Repository.
//
// 	func TestSomethingThatUsesRepository(t *testing.T) {
//
// 		// make and configure a mocked Repository
// 		mockedRepository := &RepositoryMock{
// 			CountFunc: func(contextMoqParam context.Context, uUID uuid.UUID) (int, error) {
// 				panic("mock out the Count method")
// 			},
// 			DeleteFunc: func(contextMoqParam context.Context, uUID uuid.UUID) error {
// 				panic("mock out the Delete method")
// 			},
// 			GetAllFunc: func(ctx context.Context, cursor int64, limit int) ([]News, error) {
// 				panic("mock out the GetAll method")
// 			},
// 			GetAllByStatusFunc: func(ctx context.Context, status bareknews.Status, cursor int64, limit int) ([]News, error) {
// 				panic("mock out the GetAllByStatus method")
// 			},
// 			GetAllByTopicFunc: func(ctx context.Context, id uuid.UUID, cursor int64, limit int) ([]News, error) {
// 				panic("mock out the GetAllByTopic method")
// 			},
// 			GetByIdFunc: func(contextMoqParam context.Context, uUID uuid.UUID) (*News, error) {
// 				panic("mock out the GetById method")
// 			},
// 			SaveFunc: func(contextMoqParam context.Context, news News) error {
// 				panic("mock out the Save method")
// 			},
// 			UpdateFunc: func(contextMoqParam context.Context, news News) error {
// 				panic("mock out the Update method")
// 			},
// 		}
//
// 		// use mockedRepository in code that requires Repository
// 		// and then make assertions.
//
// 	}
type RepositoryMock struct {
	// CountFunc mocks the Count method.
	CountFunc func(contextMoqParam context.Context, uUID uuid.UUID) (int, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(contextMoqParam context.Context, uUID uuid.UUID) error

	// GetAllFunc mocks the GetAll method.
	GetAllFunc func(ctx context.Context, cursor int64, limit int) ([]News, error)

	// GetAllByStatusFunc mocks the GetAllByStatus method.
	GetAllByStatusFunc func(ctx context.Context, status bareknews.Status, cursor int64, limit int) ([]News, error)

	// GetAllByTopicFunc mocks the GetAllByTopic method.
	GetAllByTopicFunc func(ctx context.Context, id uuid.UUID, cursor int64, limit int) ([]News, error)

	// GetByIdFunc mocks the GetById method.
	GetByIdFunc func(contextMoqParam context.Context, uUID uuid.UUID) (*News, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(contextMoqParam context.Context, news News) error

	// UpdateFunc mocks the Update method.
	UpdateFunc func(contextMoqParam context.Context, news News) error

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// UUID is the uUID argument value.
			UUID uuid.UUID
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// UUID is the uUID argument value.
			UUID uuid.UUID
		}
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cursor is the cursor argument value.
			Cursor int64
			// Limit is the limit argument value.
			Limit int
		}
		// GetAllByStatus holds details about calls to the GetAllByStatus method.
		GetAllByStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Status is the status argument value.
			Status bareknews.Status
			// Cursor is the cursor argument value.
			Cursor int64
			// Limit is the limit argument value.
			Limit int
		}
		// GetAllByTopic holds details about calls to the GetAllByTopic method.
		GetAllByTopic []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// Cursor is the cursor argument value.
			Cursor int64
			// Limit is the limit argument value.
			Limit int
		}
		// GetById holds details about calls to the GetById method.
		GetById []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// UUID is the uUID argument value.
			UUID uuid.UUID
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// News is the news argument value.
			News News
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// News is the news argument value.
			News News
		}
	}
	lockCount          sync.RWMutex
	lockDelete         sync.RWMutex
	lockGetAll         sync.RWMutex
	lockGetAllByStatus sync.RWMutex
	lockGetAllByTopic  sync.RWMutex
	lockGetById        sync.RWMutex
	lockSave           sync.RWMutex
	lockUpdate         sync.RWMutex
}

// Count calls CountFunc.
func (mock *RepositoryMock) Count(contextMoqParam context.Context, uUID uuid.UUID) (int, error) {
	if mock.CountFunc == nil {
		panic("RepositoryMock.CountFunc: method is nil but Repository.Count was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		UUID            uuid.UUID
	}{
		ContextMoqParam: contextMoqParam,
		UUID:            uUID,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	return mock.CountFunc(contextMoqParam, uUID)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//     len(mockedRepository.CountCalls())
func (mock *RepositoryMock) CountCalls() []struct {
	ContextMoqParam context.Context
	UUID            uuid.UUID
} {
	var calls []struct {
		ContextMoqParam context.Context
		UUID            uuid.UUID
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *RepositoryMock) Delete(contextMoqParam context.Context, uUID uuid.UUID) error {
	if mock.DeleteFunc == nil {
		panic("RepositoryMock.DeleteFunc: method is nil but Repository.Delete was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		UUID            uuid.UUID
	}{
		ContextMoqParam: contextMoqParam,
		UUID:            uUID,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(contextMoqParam, uUID)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedRepository.DeleteCalls())
func (mock *RepositoryMock) DeleteCalls() []struct {
	ContextMoqParam context.Context
	UUID            uuid.UUID
} {
	var calls []struct {
		ContextMoqParam context.Context
		UUID            uuid.UUID
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// GetAll calls GetAllFunc.
func (mock *RepositoryMock) GetAll(ctx context.Context, cursor int64, limit int) ([]News, error) {
	if mock.GetAllFunc == nil {
		panic("RepositoryMock.GetAllFunc: method is nil but Repository.GetAll was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Cursor int64
		Limit  int
	}{
		Ctx:    ctx,
		Cursor: cursor,
		Limit:  limit,
	}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	return mock.GetAllFunc(ctx, cursor, limit)
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//     len(mockedRepository.GetAllCalls())
func (mock *RepositoryMock) GetAllCalls() []struct {
	Ctx    context.Context
	Cursor int64
	Limit  int
} {
	var calls []struct {
		Ctx    context.Context
		Cursor int64
		Limit  int
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// GetAllByStatus calls GetAllByStatusFunc.
func (mock *RepositoryMock) GetAllByStatus(ctx context.Context, status bareknews.Status, cursor int64, limit int) ([]News, error) {
	if mock.GetAllByStatusFunc == nil {
		panic("RepositoryMock.GetAllByStatusFunc: method is nil but Repository.GetAllByStatus was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Status bareknews.Status
		Cursor int64
		Limit  int
	}{
		Ctx:    ctx,
		Status: status,
		Cursor: cursor,
		Limit:  limit,
	}
	mock.lockGetAllByStatus.Lock()
	mock.calls.GetAllByStatus = append(mock.calls.GetAllByStatus, callInfo)
	mock.lockGetAllByStatus.Unlock()
	return mock.GetAllByStatusFunc(ctx, status, cursor, limit)
}

// GetAllByStatusCalls gets all the calls that were made to GetAllByStatus.
// Check the length with:
//     len(mockedRepository.GetAllByStatusCalls())
func (mock *RepositoryMock) GetAllByStatusCalls() []struct {
	Ctx    context.Context
	Status bareknews.Status
	Cursor int64
	Limit  int
} {
	var calls []struct {
		Ctx    context.Context
		Status bareknews.Status
		Cursor int64
		Limit  int
	}
	mock.lockGetAllByStatus.RLock()
	calls = mock.calls.GetAllByStatus
	mock.lockGetAllByStatus.RUnlock()
	return calls
}

// GetAllByTopic calls GetAllByTopicFunc.
func (mock *RepositoryMock) GetAllByTopic(ctx context.Context, id uuid.UUID, cursor int64, limit int) ([]News, error) {
	if mock.GetAllByTopicFunc == nil {
		panic("RepositoryMock.GetAllByTopicFunc: method is nil but Repository.GetAllByTopic was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ID     uuid.UUID
		Cursor int64
		Limit  int
	}{
		Ctx:    ctx,
		ID:     id,
		Cursor: cursor,
		Limit:  limit,
	}
	mock.lockGetAllByTopic.Lock()
	mock.calls.GetAllByTopic = append(mock.calls.GetAllByTopic, callInfo)
	mock.lockGetAllByTopic.Unlock()
	return mock.GetAllByTopicFunc(ctx, id, cursor, limit)
}

// GetAllByTopicCalls gets all the calls that were made to GetAllByTopic.
// Check the length with:
//     len(mockedRepository.GetAllByTopicCalls())
func (mock *RepositoryMock) GetAllByTopicCalls() []struct {
	Ctx    context.Context
	ID     uuid.UUID
	Cursor int64
	Limit  int
} {
	var calls []struct {
		Ctx    context.Context
		ID     uuid.UUID
		Cursor int64
		Limit  int
	}
	mock.lockGetAllByTopic.RLock()
	calls = mock.calls.GetAllByTopic
	mock.lockGetAllByTopic.RUnlock()
	return calls
}

// GetById calls GetByIdFunc.
func (mock *RepositoryMock) GetById(contextMoqParam context.Context, uUID uuid.UUID) (*News, error) {
	if mock.GetByIdFunc == nil {
		panic("RepositoryMock.GetByIdFunc: method is nil but Repository.GetById was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		UUID            uuid.UUID
	}{
		ContextMoqParam: contextMoqParam,
		UUID:            uUID,
	}
	mock.lockGetById.Lock()
	mock.calls.GetById = append(mock.calls.GetById, callInfo)
	mock.lockGetById.Unlock()
	return mock.GetByIdFunc(contextMoqParam, uUID)
}

// GetByIdCalls gets all the calls that were made to GetById.
// Check the length with:
//     len(mockedRepository.GetByIdCalls())
func (mock *RepositoryMock) GetByIdCalls() []struct {
	ContextMoqParam context.Context
	UUID            uuid.UUID
} {
	var calls []struct {
		ContextMoqParam context.Context
		UUID            uuid.UUID
	}
	mock.lockGetById.RLock()
	calls = mock.calls.GetById
	mock.lockGetById.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *RepositoryMock) Save(contextMoqParam context.Context, news News) error {
	if mock.SaveFunc == nil {
		panic("RepositoryMock.SaveFunc: method is nil but Repository.Save was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		News            News
	}{
		ContextMoqParam: contextMoqParam,
		News:            news,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(contextMoqParam, news)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//     len(mockedRepository.SaveCalls())
func (mock *RepositoryMock) SaveCalls() []struct {
	ContextMoqParam context.Context
	News            News
} {
	var calls []struct {
		ContextMoqParam context.Context
		News            News
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *RepositoryMock) Update(contextMoqParam context.Context, news News) error {
	if mock.UpdateFunc == nil {
		panic("RepositoryMock.UpdateFunc: method is nil but Repository.Update was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		News            News
	}{
		ContextMoqParam: contextMoqParam,
		News:            news,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(contextMoqParam, news)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedRepository.UpdateCalls())
func (mock *RepositoryMock) UpdateCalls() []struct {
	ContextMoqParam context.Context
	News            News
} {
	var calls []struct {
		ContextMoqParam context.Context
		News            News
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}