// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package tags

import (
	"github.com/google/uuid"
	"sync"
)

// Ensure, that RepositoryMock does implement Repository.
// If this is not the case, regenerate this file with moq.
var _ Repository = &RepositoryMock{}

// RepositoryMock is a mock implementation of Repository.
//
// 	func TestSomethingThatUsesRepository(t *testing.T) {
//
// 		// make and configure a mocked Repository
// 		mockedRepository := &RepositoryMock{
// 			CountFunc: func(id uuid.UUID) (int, error) {
// 				panic("mock out the Count method")
// 			},
// 			DeleteFunc: func(id uuid.UUID) error {
// 				panic("mock out the Delete method")
// 			},
// 			GetAllFunc: func() ([]Tags, error) {
// 				panic("mock out the GetAll method")
// 			},
// 			GetByIdFunc: func(id uuid.UUID) (*Tags, error) {
// 				panic("mock out the GetById method")
// 			},
// 			GetByIdsFunc: func(ids []uuid.UUID) ([]Tags, error) {
// 				panic("mock out the GetByIds method")
// 			},
// 			GetByNamesFunc: func(names ...string) ([]Tags, error) {
// 				panic("mock out the GetByNames method")
// 			},
// 			SaveFunc: func(tags Tags) error {
// 				panic("mock out the Save method")
// 			},
// 			UpdateFunc: func(tags Tags) error {
// 				panic("mock out the Update method")
// 			},
// 		}
//
// 		// use mockedRepository in code that requires Repository
// 		// and then make assertions.
//
// 	}
type RepositoryMock struct {
	// CountFunc mocks the Count method.
	CountFunc func(id uuid.UUID) (int, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(id uuid.UUID) error

	// GetAllFunc mocks the GetAll method.
	GetAllFunc func() ([]Tags, error)

	// GetByIdFunc mocks the GetById method.
	GetByIdFunc func(id uuid.UUID) (*Tags, error)

	// GetByIdsFunc mocks the GetByIds method.
	GetByIdsFunc func(ids []uuid.UUID) ([]Tags, error)

	// GetByNamesFunc mocks the GetByNames method.
	GetByNamesFunc func(names ...string) ([]Tags, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(tags Tags) error

	// UpdateFunc mocks the Update method.
	UpdateFunc func(tags Tags) error

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// ID is the id argument value.
			ID uuid.UUID
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
		}
		// GetById holds details about calls to the GetById method.
		GetById []struct {
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetByIds holds details about calls to the GetByIds method.
		GetByIds []struct {
			// Ids is the ids argument value.
			Ids []uuid.UUID
		}
		// GetByNames holds details about calls to the GetByNames method.
		GetByNames []struct {
			// Names is the names argument value.
			Names []string
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Tags is the tags argument value.
			Tags Tags
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Tags is the tags argument value.
			Tags Tags
		}
	}
	lockCount      sync.RWMutex
	lockDelete     sync.RWMutex
	lockGetAll     sync.RWMutex
	lockGetById    sync.RWMutex
	lockGetByIds   sync.RWMutex
	lockGetByNames sync.RWMutex
	lockSave       sync.RWMutex
	lockUpdate     sync.RWMutex
}

// Count calls CountFunc.
func (mock *RepositoryMock) Count(id uuid.UUID) (int, error) {
	if mock.CountFunc == nil {
		panic("RepositoryMock.CountFunc: method is nil but Repository.Count was just called")
	}
	callInfo := struct {
		ID uuid.UUID
	}{
		ID: id,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	return mock.CountFunc(id)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//     len(mockedRepository.CountCalls())
func (mock *RepositoryMock) CountCalls() []struct {
	ID uuid.UUID
} {
	var calls []struct {
		ID uuid.UUID
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *RepositoryMock) Delete(id uuid.UUID) error {
	if mock.DeleteFunc == nil {
		panic("RepositoryMock.DeleteFunc: method is nil but Repository.Delete was just called")
	}
	callInfo := struct {
		ID uuid.UUID
	}{
		ID: id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedRepository.DeleteCalls())
func (mock *RepositoryMock) DeleteCalls() []struct {
	ID uuid.UUID
} {
	var calls []struct {
		ID uuid.UUID
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// GetAll calls GetAllFunc.
func (mock *RepositoryMock) GetAll() ([]Tags, error) {
	if mock.GetAllFunc == nil {
		panic("RepositoryMock.GetAllFunc: method is nil but Repository.GetAll was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	return mock.GetAllFunc()
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//     len(mockedRepository.GetAllCalls())
func (mock *RepositoryMock) GetAllCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// GetById calls GetByIdFunc.
func (mock *RepositoryMock) GetById(id uuid.UUID) (*Tags, error) {
	if mock.GetByIdFunc == nil {
		panic("RepositoryMock.GetByIdFunc: method is nil but Repository.GetById was just called")
	}
	callInfo := struct {
		ID uuid.UUID
	}{
		ID: id,
	}
	mock.lockGetById.Lock()
	mock.calls.GetById = append(mock.calls.GetById, callInfo)
	mock.lockGetById.Unlock()
	return mock.GetByIdFunc(id)
}

// GetByIdCalls gets all the calls that were made to GetById.
// Check the length with:
//     len(mockedRepository.GetByIdCalls())
func (mock *RepositoryMock) GetByIdCalls() []struct {
	ID uuid.UUID
} {
	var calls []struct {
		ID uuid.UUID
	}
	mock.lockGetById.RLock()
	calls = mock.calls.GetById
	mock.lockGetById.RUnlock()
	return calls
}

// GetByIds calls GetByIdsFunc.
func (mock *RepositoryMock) GetByIds(ids []uuid.UUID) ([]Tags, error) {
	if mock.GetByIdsFunc == nil {
		panic("RepositoryMock.GetByIdsFunc: method is nil but Repository.GetByIds was just called")
	}
	callInfo := struct {
		Ids []uuid.UUID
	}{
		Ids: ids,
	}
	mock.lockGetByIds.Lock()
	mock.calls.GetByIds = append(mock.calls.GetByIds, callInfo)
	mock.lockGetByIds.Unlock()
	return mock.GetByIdsFunc(ids)
}

// GetByIdsCalls gets all the calls that were made to GetByIds.
// Check the length with:
//     len(mockedRepository.GetByIdsCalls())
func (mock *RepositoryMock) GetByIdsCalls() []struct {
	Ids []uuid.UUID
} {
	var calls []struct {
		Ids []uuid.UUID
	}
	mock.lockGetByIds.RLock()
	calls = mock.calls.GetByIds
	mock.lockGetByIds.RUnlock()
	return calls
}

// GetByNames calls GetByNamesFunc.
func (mock *RepositoryMock) GetByNames(names ...string) ([]Tags, error) {
	if mock.GetByNamesFunc == nil {
		panic("RepositoryMock.GetByNamesFunc: method is nil but Repository.GetByNames was just called")
	}
	callInfo := struct {
		Names []string
	}{
		Names: names,
	}
	mock.lockGetByNames.Lock()
	mock.calls.GetByNames = append(mock.calls.GetByNames, callInfo)
	mock.lockGetByNames.Unlock()
	return mock.GetByNamesFunc(names...)
}

// GetByNamesCalls gets all the calls that were made to GetByNames.
// Check the length with:
//     len(mockedRepository.GetByNamesCalls())
func (mock *RepositoryMock) GetByNamesCalls() []struct {
	Names []string
} {
	var calls []struct {
		Names []string
	}
	mock.lockGetByNames.RLock()
	calls = mock.calls.GetByNames
	mock.lockGetByNames.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *RepositoryMock) Save(tags Tags) error {
	if mock.SaveFunc == nil {
		panic("RepositoryMock.SaveFunc: method is nil but Repository.Save was just called")
	}
	callInfo := struct {
		Tags Tags
	}{
		Tags: tags,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(tags)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//     len(mockedRepository.SaveCalls())
func (mock *RepositoryMock) SaveCalls() []struct {
	Tags Tags
} {
	var calls []struct {
		Tags Tags
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *RepositoryMock) Update(tags Tags) error {
	if mock.UpdateFunc == nil {
		panic("RepositoryMock.UpdateFunc: method is nil but Repository.Update was just called")
	}
	callInfo := struct {
		Tags Tags
	}{
		Tags: tags,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(tags)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedRepository.UpdateCalls())
func (mock *RepositoryMock) UpdateCalls() []struct {
	Tags Tags
} {
	var calls []struct {
		Tags Tags
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
